### ISSUE TITLE
External packages task list

### ISSUE THREAD

**Issue by drot** [wasamasa/gotham-theme#25]
### Current plans

- [x] SLIME support (done, waiting for review)

- [x] Gnus support (done, waiting for review)

- [x] Avy (done, waiting for review)

- [x] Ace-window (done, waiting for review)

- [x] Geiser (done, waiting for review)

- [x] Lispy (done, waiting for review)

- [x] NeoTree (done, waiting for review)

- [x] Ruler (done, waiting for review)

I'll add probably some more as I stumble upon them.

**Comment by drot** [comment]
Well I can finally close this one. Thanks!
